#
# Module manifest for module 'khyperv-csi'
#
# Generated by: Alistair Mackay
#
# Generated on: 28/09/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'khyperv-csi.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '057fb3ab-8585-4f34-8d26-4a70fd551de4'

# Author of this module
Author = 'Alistair Mackay'

# Company or vendor of this module
CompanyName = 'Firefly Consulting Ltd'

# Copyright statement for this module
Copyright = '(c) 2025 Alistair Mackay. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Implementation of Hyper-V CSI controller backend'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Hyper-V')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Dismount-Disk', 'Get-Attachments', 'Get-Capacity', 'Get-Disk', 'Get-Disks', 'Get-Store',
               'Get-VMId', 'Get-VirtualMachines', 'Mount-Disk', 'New-Disk', 'New-TestVM', 'Remove-Disk',
               'Test-Exception'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # External dependent modules of this module
        ExternalModuleDependencies = @('Hyper-V')

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
DefaultCommandPrefix = 'PV'

}

