apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-hv-node-sa
  labels:
    {{- include "chart.labels" . | nindent 4 }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-hv-node-driver-registrar-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-hv-node-driver-registrar-binding
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: csi-hv-node-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-hv-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io