package shared

import (
	"fmt"
	"runtime"

	"github.com/fireflycons/hypervcsi/internal/common"
	"github.com/spf13/cobra"
)

var sysinfoCmd = &cobra.Command{
	Use:   "sysinfo",
	Short: "Print system information and exit",
	Long:  longDescription(),
	Run: func(*cobra.Command, []string) {
		fmt.Println(common.GetSystemInfo())
	},
}

func InitSysinfoCmd(rootCmd *cobra.Command) {
	rootCmd.AddCommand(sysinfoCmd)
}

func longDescription() string {

	desc := "If filing an issue in gitub, please include the report generated by this command"

	if runtime.GOOS != "windows" {
		desc += `

Retrieve the output from within the pod to properly capture the execution environment:

` + "```\nkubectl exec csi-hv-controller-0 -- hyperv-csi-plugin sysinfo\n```\n"

	}

	desc += `

If the output indicates a newer version is available, check the release notes on github
as your issue may already be addressed.
`

	return desc
}
