// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hyperv

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// newMockhttpClient creates a new instance of mockhttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhttpClient {
	mock := &mockhttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhttpClient is an autogenerated mock type for the httpClient type
type mockhttpClient struct {
	mock.Mock
}

type mockhttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhttpClient) EXPECT() *mockhttpClient_Expecter {
	return &mockhttpClient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type mockhttpClient
func (_mock *mockhttpClient) Do(request *http.Request) (*http.Response, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockhttpClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type mockhttpClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - request *http.Request
func (_e *mockhttpClient_Expecter) Do(request interface{}) *mockhttpClient_Do_Call {
	return &mockhttpClient_Do_Call{Call: _e.mock.On("Do", request)}
}

func (_c *mockhttpClient_Do_Call) Run(run func(request *http.Request)) *mockhttpClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhttpClient_Do_Call) Return(response *http.Response, err error) *mockhttpClient_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *mockhttpClient_Do_Call) RunAndReturn(run func(request *http.Request) (*http.Response, error)) *mockhttpClient_Do_Call {
	_c.Call.Return(run)
	return _c
}
