name: build
on: [push, pull_request]
jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # so we can diff against previous commit

      - id: check
        run: |
          echo "Checking conditions to skip workflow..."

          # Get latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Check for NO-CI
          if echo "$COMMIT_MSG" | grep -q "NO-CI"; then
            echo "NO-CI found in commit message. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get changed files
          CHANGED=$(git diff --name-only HEAD~1)
          echo "Changed files:"
          echo "$CHANGED"

          # If all changed files are markdown
          if [ -n "$CHANGED" ] && ! echo "$CHANGED" | grep -vqE '\.md$'; then
            echo "Only markdown files changed. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "No skip conditions met."
          echo "skip=false" >> $GITHUB_OUTPUT

  lint:
    needs: precheck
    if: ${{ needs.precheck.outputs.skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

  windows-service:
    needs: lint
    runs-on: windows-2022
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: |
          make -v
          make windows-service
        shell: cmd

      - name: Test
        run: make test
        shell: cmd

  cluster-components:
    needs: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Test
        run: make test

